In [41]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()

from sklearn.linear_model import LogisticRegression
log=LogisticRegression()

from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

# Simple imputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

#knn imputer
from sklearn.impute import KNNImputer

import warnings
warnings.filterwarnings("ignore")


In [27]:
data={"SibSp":[1,1,0,1,0,0],"Fare":[7.2500,71.2833,7.2950,53.1000,8.0500,8.4583],"Age":[22,38,26,35,35,np.NaN]}
data

X=pd.DataFrame(data)
X

SibSp     Fare   Age
0      1   7.2500  22.0
1      1  71.2833  38.0
2      0   7.2950  26.0
3      1  53.1000  35.0
4      0   8.0500  35.0
5      0   8.4583   NaN

In [20]:
# iterative imputer 

In [28]:
impute=IterativeImputer(lr)
impute.fit_transform(X)

array([[ 1.        ,  7.25      , 22.        ],
       [ 1.        , 71.2833    , 38.        ],
       [ 0.        ,  7.295     , 26.        ],
       [ 1.        , 53.1       , 35.        ],
       [ 0.        ,  8.05      , 35.        ],
       [ 0.        ,  8.4583    , 30.70268349]])

In [29]:
impute=IterativeImputer(rfr)
impute.fit_transform(X)

array([[ 1.    ,  7.25  , 22.    ],
       [ 1.    , 71.2833, 38.    ],
       [ 0.    ,  7.295 , 26.    ],
       [ 1.    , 53.1   , 35.    ],
       [ 0.    ,  8.05  , 35.    ],
       [ 0.    ,  8.4583, 32.15  ]])

In [ ]:
# on the data

In [9]:
data=pd.read_table("C:/Users/rijul/Downloads/horse-colic.txt",delimiter=",",header=None,na_values="?")
data.shape
data.isnull().sum()

0       1
1       0
2       0
3      60
4      24
5      58
6      56
7      69
8      47
9      32
10     55
11     44
12     56
13    104
14    106
15    247
16    102
17    118
18     29
19     33
20    165
21    198
22      1
23      0
24      0
25      0
26      0
27      0
dtype: int64

In [32]:
# on default  settings
# by default ml algo is bayesianRidge
data.shape
data.isnull().sum()
impute=IterativeImputer()
pd.DataFrame(impute.fit_transform(data)).head()


AttributeError: 'dict' object has no attribute 'shape'

In [31]:
new=pd.read_csv("C:/Users/rijul/Downloads/Same_Score_FullData.csv")
new.iloc[:,1:]

Section  Test1  Test2  Final
0         1     94     91     87
1         2     51     65     91
2         1     95     97     97
3         2     63     75     80
4         2     80     76     71
5         1     92     40     86
6         1     75     78     72
7         1     94     91     87
8         2     51     65     91
9         1     95     97     97
10        2     63     75     80
11        2     80     76     71
12        1     92     40     86
13        1     75     78     72

In [16]:
score=pd.read_csv("C:/Users/rijul/Downloads/Same_Missing_Score.csv")
score=score.iloc[:,1:]
score

Section  Test1  Test2  Final
0       1.0     94     91     87
1       2.0     51     65     91
2       1.0     95     97     97
3       NaN     63     75     80
4       2.0     80     76     71
5       NaN     92     40     86
6       1.0     75     78     72
7       1.0     94     91     87
8       NaN     51     65     91
9       1.0     95     97     97
10      2.0     63     75     80
11      2.0     80     76     71
12      1.0     92     40     86
13      NaN     75     78     72

In [34]:
# on linear regression
impute=IterativeImputer(lr)
pd.DataFrame(impute.fit_transform(data)).head()

TypeError: float() argument must be a string or a number, not 'dict'

In [43]:
# with logistic regression
impute=IterativeImputer(log)
pd.DataFrame(impute.fit_transform(score),columns=["Section","Test1","Test2","Final"])

Section  Test1  Test2  Final
0       1.0   94.0   91.0   87.0
1       2.0   51.0   65.0   91.0
2       1.0   95.0   97.0   97.0
3       2.0   63.0   75.0   80.0
4       2.0   80.0   76.0   71.0
5       1.0   92.0   40.0   86.0
6       1.0   75.0   78.0   72.0
7       1.0   94.0   91.0   87.0
8       2.0   51.0   65.0   91.0
9       1.0   95.0   97.0   97.0
10      2.0   63.0   75.0   80.0
11      2.0   80.0   76.0   71.0
12      1.0   92.0   40.0   86.0
13      2.0   75.0   78.0   72.0

In [42]:
# on randomforest regressor
impute=IterativeImputer(rf)
pd.DataFrame(impute.fit_transform(data)).head()

TypeError: float() argument must be a string or a number, not 'dict'

In [44]:
# knn imputer

In [50]:
X
# print((26+35+22)/3)

SibSp     Fare   Age
0      1   7.2500  22.0
1      1  71.2833  38.0
2      0   7.2950  26.0
3      1  53.1000  35.0
4      0   8.0500  35.0
5      0   8.4583   NaN

In [46]:
knn=KNNImputer(n_neighbors=2)
knn.fit_transform(X)


array([[ 1.    ,  7.25  , 22.    ],
       [ 1.    , 71.2833, 38.    ],
       [ 0.    ,  7.295 , 26.    ],
       [ 1.    , 53.1   , 35.    ],
       [ 0.    ,  8.05  , 35.    ],
       [ 0.    ,  8.4583, 30.5   ]])