In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
data = pd.read_csv("C:/Users/rijul/Downloads/predict_admission.csv")
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [16]:
#Initializing the variables
X = data.drop(['Serial No.','Chance of Admit '], axis=1)
y = data['Chance of Admit '].values.reshape(-1,1)

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=65)

In [20]:
from sklearn.linear_model import LinearRegression
multiple_reg = LinearRegression()
multiple_reg.fit(X_train, y_train)

LinearRegression()

In [21]:
y_pred = multiple_reg.predict(X_test)

In [22]:
y_pred

array([[0.53215137],
       [0.77959642],
       [0.6131636 ],
       [0.90607044],
       [0.61538968],
       [0.63067354],
       [0.88745871],
       [0.83855941],
       [0.81642923],
       [0.81476867],
       [0.83991844],
       [0.92026338],
       [0.73404168],
       [0.50712609],
       [0.79443359],
       [0.440842  ],
       [0.85064681],
       [0.53824659],
       [0.83030373],
       [0.94455701],
       [0.67994403],
       [0.75874984],
       [0.91017025],
       [0.65006473],
       [0.6042326 ],
       [0.71416376],
       [0.45389828],
       [0.94844768],
       [0.80333838],
       [0.53361576],
       [0.94973465],
       [0.99549934],
       [0.51614161],
       [0.67399029],
       [0.51867275],
       [0.59921965],
       [0.81292198],
       [0.85491434],
       [0.55464475],
       [0.91124528],
       [0.77139992],
       [0.86558213],
       [0.46043214],
       [0.79496049],
       [0.81940702],
       [0.57848565],
       [0.64701062],
       [0.658

In [24]:
y_test
X_test

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
37         300          105                  1  1.0   2.0  7.80         0
222        324          113                  4  4.5   4.0  8.79         0
407        298          100                  3  2.5   4.0  7.95         1
362        338          115                  5  4.5   5.0  9.23         1
413        317          101                  3  3.0   2.0  7.94         1
..         ...          ...                ...  ...   ...   ...       ...
221        316          110                  3  3.5   4.0  8.56         0
390        314          102                  2  2.0   2.5  8.24         0
274        315          100                  1  2.0   2.5  7.95         0
137        316          100                  2  1.5   3.0  8.16         1
383        300          100                  3  3.0   3.5  8.26         0

[100 rows x 7 columns]

In [25]:
X_test
y_train

array([[0.9 ],
       [0.79],
       [0.72],
       [0.64],
       [0.91],
       [0.71],
       [0.87],
       [0.77],
       [0.62],
       [0.62],
       [0.74],
       [0.64],
       [0.84],
       [0.5 ],
       [0.73],
       [0.66],
       [0.61],
       [0.52],
       [0.42],
       [0.72],
       [0.71],
       [0.38],
       [0.49],
       [0.86],
       [0.8 ],
       [0.71],
       [0.64],
       [0.57],
       [0.71],
       [0.72],
       [0.68],
       [0.84],
       [0.79],
       [0.67],
       [0.73],
       [0.67],
       [0.71],
       [0.57],
       [0.78],
       [0.56],
       [0.81],
       [0.57],
       [0.74],
       [0.61],
       [0.77],
       [0.46],
       [0.7 ],
       [0.81],
       [0.67],
       [0.66],
       [0.91],
       [0.68],
       [0.82],
       [0.61],
       [0.84],
       [0.71],
       [0.76],
       [0.71],
       [0.94],
       [0.73],
       [0.96],
       [0.59],
       [0.79],
       [0.73],
       [0.8 ],
       [0.73],
       [0.

In [26]:
y_test
X_train

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
141        332          118                  2  4.5   3.5  9.36         1
289        313          109                  3  4.0   3.5  9.00         0
2          316          104                  3  3.0   3.5  8.00         1
168        293           97                  2  2.0   4.0  7.80         1
234        330          113                  5  5.0   4.0  9.31         1
..         ...          ...                ...  ...   ...   ...       ...
213        333          119                  5  5.0   4.5  9.78         1
296        310          107                  3  3.5   3.5  8.67         0
63         315          107                  2  4.0   3.0  8.50         1
117        290          104                  4  2.0   2.5  7.46         0
302        322          105                  2  3.0   3.0  8.45         1

[400 rows x 7 columns]

In [27]:
new=[]
for i in range(3):
    new.append(multiple_reg.coef_[0][i])

In [28]:
multiple_reg.coef_

array([[0.00143034, 0.00299646, 0.00571851, 0.00746991, 0.01525848,
        0.11649289, 0.02822243]])

In [29]:
multiple_reg.intercept_

array([-1.16392983])

In [30]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8704504365542649