In [2]:
# Diff between arange and array object
import numpy as np
arr = np.arange(0,10)
arr1 = np.arange(0,11)
arr2 = np.arange(0,12)

In [3]:
arr2.shape

(12,)

In [4]:
arr1.shape
arr.shape

(10,)

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr / arr

<ipython-input-8-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
# also warning, but not an error instead infinity

print(arr1)
11/arr1
#(np.arrange(10,20))/10

[ 0  1  2  3  4  5  6  7  8  9 10]


<ipython-input-9-0903f59adb9d>:4: RuntimeWarning: divide by zero encountered in true_divide
  11/arr1


array([        inf, 11.        ,  5.5       ,  3.66666667,  2.75      ,
        2.2       ,  1.83333333,  1.57142857,  1.375     ,  1.22222222,
        1.1       ])

In [10]:
arr1**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [12]:
x = np.arange(1,10)
y = np.array(10)
print(x)
print(y)

[1 2 3 4 5 6 7 8 9]
10


In [13]:
z = x+y
z
print(x,"X")
print(y,"Y")
print(z,"Z")

[1 2 3 4 5 6 7 8 9] X
10 Y
[11 12 13 14 15 16 17 18 19] Z


In [14]:
# appending new elements into the existing numpy array object
asd=np.arange(0,10)
sun=np.append(asd,[55,66,77,22,45,44])
sun

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 55, 66, 77, 22, 45, 44])

In [15]:
#deleting any element in array
sun=np.delete(sun,10)
sun

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 66, 77, 22, 45, 44])

In [ ]:
# UNIVERSAL ARRAY FUNCTIONS

In [16]:
# taking square roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [17]:
# calculating exponential(e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [18]:
np.max(arr)# same as arr.max()
#arr.max()

9

In [19]:
np.min(arr)#same as arr.min()
#arr.min()

0

In [20]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [21]:
np.log(arr)

<ipython-input-21-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [22]:
np.mean(arr)#Mean

4.5