In [1]:
#IMPORTING THE LIBRARIES
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# Importing the placement data
pla=pd.read_csv("C:/Users/rijul/Downloads/Placement_Data.csv")
pla.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [3]:
# Importing the Car data
car = pd.read_csv("C:/Users/rijul/Downloads/Car_Sales.csv")
car.head()

Manufacturer              Model  Sales in thousands  x_4_year  \
0  Acura          Integra                        16.919    16.360   
1  Acura          TL                             39.384    19.875   
2  Acura          CL                             14.114    18.225   
3  Acura          RL                              8.588    29.725   
4  Audi           A4                             20.397    22.255   

  Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  Width  \
0    Passenger               21.50          1.8       140.0      101.2   67.3   
1    Passenger               28.40          3.2       225.0      108.1   70.3   
2    Passenger                 NaN          3.2       225.0      106.9   70.6   
3    Passenger               42.00          3.5       210.0      114.6   71.4   
4    Passenger               23.99          1.8       150.0      102.6   68.2   

   Length  Curb weight  Fuel capacity  Fuel efficiency Latest Launch  \
0   172.4        2.639           13.2             28.0      2-Feb-14   
1   192.9        3.517           17.2             25.0      6-Mar-15   
2   192.0        3.470           17.2             26.0      1-Apr-14   
3   196.6        3.850           18.0             22.0      3-Oct-15   
4   178.0        2.998           16.4             27.0     10-Aug-15   

   Unnamed: 15      XX  
0          NaN  16.360  
1          NaN  19.875  
2          NaN  18.225  
3          NaN  29.725  
4          NaN  22.255

In [4]:
# No. of columns in car data
car.columns

Index(['Manufacturer', 'Model', 'Sales in thousands', 'x_4_year',
       'Vehicle type', 'Price in thousands', 'Engine size', 'Horsepower',
       'Wheelbase', 'Width', 'Length', 'Curb weight', 'Fuel capacity',
       'Fuel efficiency', 'Latest Launch', 'Unnamed: 15', 'XX'],
      dtype='object')

In [5]:
car.isnull().sum()

Manufacturer            0
Model                   0
Sales in thousands      0
x_4_year               36
Vehicle type            0
Price in thousands      2
Engine size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb weight             2
Fuel capacity           1
Fuel efficiency         3
Latest Launch           0
Unnamed: 15           157
XX                     36
dtype: int64

In [6]:
car["Manufacturer"].value_counts()

Dodge            11
Ford             11
Mercedes-Benz     9
Chevrolet         9
Toyota            9
Nissan            7
Chrysler          7
Mitsubishi        7
Volvo             6
Mercury           6
Volkswagen        6
Oldsmobile        6
Pontiac           6
Lexus             6
Saturn            5
Cadillac          5
Honda             5
Buick             4
Acura             4
Plymouth          4
Audi              3
BMW               3
Lincoln           3
Jeep              3
Porsche           3
Hyundai           3
Saab              2
Subaru            2
Infiniti          1
Jaguar            1
Name: Manufacturer, dtype: int64

In [7]:
car["Sales in thousands"].value_counts()

19.911    1
73.203    1
9.569     1
33.269    1
83.257    1
         ..
17.527    1
12.855    1
51.645    1
48.911    1
70.227    1
Name: Sales in thousands, Length: 157, dtype: int64

In [8]:
car['Manufacturer'].fillna("BMW",inplace=True)

In [9]:
#Discovering Missing Values
car.isnull().sum()

Manufacturer            0
Model                   0
Sales in thousands      0
x_4_year               36
Vehicle type            0
Price in thousands      2
Engine size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb weight             2
Fuel capacity           1
Fuel efficiency         3
Latest Launch           0
Unnamed: 15           157
XX                     36
dtype: int64

In [10]:
# Treat all the missing values with mean/median or most occuring observation.

In [11]:
# print(placement['gender'].notnull())
pla['ssc_p'].mean()
pla['ssc_p'].isnull()
pla['ssc_p']=pla['ssc_p'].fillna(pla['ssc_p'].mean())

In [12]:
pla

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0        1      M  67.00   Others  91.00   Others  Commerce     58.00   
1        2      M  79.33  Central  78.33   Others   Science     77.48   
2        3      M  65.00  Central  68.00  Central      Arts     64.00   
3        4      M  56.00  Central  52.00  Central   Science     52.00   
4        5      M  85.80  Central  73.60  Central  Commerce     73.30   
..     ...    ...    ...      ...    ...      ...       ...       ...   
210    211      M  80.60   Others  82.00   Others  Commerce     77.60   
211    212      M  58.00   Others  60.00   Others   Science     72.00   
212    213      M  67.00   Others  67.00   Others  Commerce     73.00   
213    214      F  74.00   Others  66.00   Others  Commerce     58.00   
214    215      M  62.00  Central  58.00   Others   Science     53.00   

      degree_t workex  etest_p specialisation  mba_p      status    salary  
0     Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1     Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2    Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3     Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4    Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0  
..         ...    ...      ...            ...    ...         ...       ...  
210  Comm&Mgmt     No     91.0        Mkt&Fin  74.49      Placed  400000.0  
211   Sci&Tech     No     74.0        Mkt&Fin  53.62      Placed  275000.0  
212  Comm&Mgmt    Yes     59.0        Mkt&Fin  69.72      Placed  295000.0  
213  Comm&Mgmt     No     70.0         Mkt&HR  60.23      Placed  204000.0  
214  Comm&Mgmt     No     89.0         Mkt&HR  60.22  Not Placed       NaN  

[215 rows x 15 columns]

In [13]:
car['Sales in thousands']=car['Sales in thousands'].fillna(car['Sales in thousands'].mean())
car['x_4_year']=car['x_4_year'].fillna(car['x_4_year'].mean())
car['Price in thousands']=car['Price in thousands'].fillna(car['Price in thousands'].mean())
car['Engine size']=car['Engine size'].fillna(car['Engine size'].mean())
car['Horsepower']=car['Horsepower'].fillna(car['Horsepower'].mean())
car['Wheelbase']=car['Wheelbase'].fillna(car['Wheelbase'].mean())
car['Width']=car['Width'].fillna(car['Width'].mean())
car['Length']=car['Length'].fillna(car['Length'].mean())
car['Curb weight']=car['Curb weight'].fillna(car['Curb weight'].mean())
car['Fuel capacity']=car['Fuel capacity'].fillna(car['Fuel capacity'].mean())
car['Unnamed: 15']=car['Unnamed: 15'].fillna(car['Unnamed: 15'].mean())
car['XX']=car['XX'].fillna(car['XX'].mean())
car

Manufacturer              Model  Sales in thousands   x_4_year  \
0    Acura          Integra                        16.919  16.360000   
1    Acura          TL                             39.384  19.875000   
2    Acura          CL                             14.114  18.225000   
3    Acura          RL                              8.588  29.725000   
4    Audi           A4                             20.397  22.255000   
..             ...                ...                 ...        ...   
152  Volvo          V40                             3.545  18.072975   
153  Volvo          S70                            15.245  18.072975   
154  Volvo          V70                            17.531  18.072975   
155  Volvo          C70                             3.493  18.072975   
156  Volvo          S80                            18.969  18.072975   

    Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  \
0      Passenger           21.500000          1.8       140.0      101.2   
1      Passenger           28.400000          3.2       225.0      108.1   
2      Passenger           27.390755          3.2       225.0      106.9   
3      Passenger           42.000000          3.5       210.0      114.6   
4      Passenger           23.990000          1.8       150.0      102.6   
..           ...                 ...          ...         ...        ...   
152    Passenger           24.400000          1.9       160.0      100.5   
153    Passenger           27.500000          2.4       168.0      104.9   
154    Passenger           28.800000          2.4       168.0      104.9   
155    Passenger           45.500000          2.3       236.0      104.9   
156    Passenger           36.000000          2.9       201.0      109.9   

     Width  Length  Curb weight  Fuel capacity  Fuel efficiency Latest Launch  \
0     67.3   172.4        2.639           13.2             28.0      2-Feb-14   
1     70.3   192.9        3.517           17.2             25.0      6-Mar-15   
2     70.6   192.0        3.470           17.2             26.0      1-Apr-14   
3     71.4   196.6        3.850           18.0             22.0      3-Oct-15   
4     68.2   178.0        2.998           16.4             27.0     10-Aug-15   
..     ...     ...          ...            ...              ...           ...   
152   67.6   176.6        3.042           15.8             25.0     21-Sep-15   
153   69.3   185.9        3.208           17.9             25.0     24-Nov-14   
154   69.3   186.2        3.259           17.9             25.0     25-Jun-15   
155   71.5   185.7        3.601           18.5             23.0     26-Apr-15   
156   72.1   189.8        3.600           21.1             24.0     14-Nov-15   

     Unnamed: 15         XX  
0            NaN  16.360000  
1            NaN  19.875000  
2            NaN  18.225000  
3            NaN  29.725000  
4            NaN  22.255000  
..           ...        ...  
152          NaN  18.072975  
153          NaN  18.072975  
154          NaN  18.072975  
155          NaN  18.072975  
156          NaN  18.072975  

[157 rows x 17 columns]

In [ ]:
pla['hsc_p']=pla['hsc_p'].fillna(pla['hsc_p'].mean())
pla['degree_p']=pla['degree_p'].fillna(pla['degree_p'].mean())
pla['etest_p']=pla['etest_p'].fillna(pla['etest_p'].mean())
pla['mba_p']=pla['mba_p'].fillna(pla['mba_p'].mean())
pla['salary']=pla['salary'].fillna(pla['salary'].mean())
pla

In [ ]:
# Check the no. of rows and no. of columns in placement data.

In [14]:
len(pla.columns)

15

In [15]:
len(pla.index)

215

In [16]:
# Check the no. of columns and rows in car data

In [17]:
len(car.columns)

17

In [18]:
len(car.index)

157

In [19]:
# Remove unnecessary columns from the placement or car data.

In [20]:
car.drop(['Latest Launch','Unnamed: 15','XX'],inplace=True, axis=1)

In [21]:
car

Manufacturer              Model  Sales in thousands   x_4_year  \
0    Acura          Integra                        16.919  16.360000   
1    Acura          TL                             39.384  19.875000   
2    Acura          CL                             14.114  18.225000   
3    Acura          RL                              8.588  29.725000   
4    Audi           A4                             20.397  22.255000   
..             ...                ...                 ...        ...   
152  Volvo          V40                             3.545  18.072975   
153  Volvo          S70                            15.245  18.072975   
154  Volvo          V70                            17.531  18.072975   
155  Volvo          C70                             3.493  18.072975   
156  Volvo          S80                            18.969  18.072975   

    Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  \
0      Passenger           21.500000          1.8       140.0      101.2   
1      Passenger           28.400000          3.2       225.0      108.1   
2      Passenger           27.390755          3.2       225.0      106.9   
3      Passenger           42.000000          3.5       210.0      114.6   
4      Passenger           23.990000          1.8       150.0      102.6   
..           ...                 ...          ...         ...        ...   
152    Passenger           24.400000          1.9       160.0      100.5   
153    Passenger           27.500000          2.4       168.0      104.9   
154    Passenger           28.800000          2.4       168.0      104.9   
155    Passenger           45.500000          2.3       236.0      104.9   
156    Passenger           36.000000          2.9       201.0      109.9   

     Width  Length  Curb weight  Fuel capacity  Fuel efficiency  
0     67.3   172.4        2.639           13.2             28.0  
1     70.3   192.9        3.517           17.2             25.0  
2     70.6   192.0        3.470           17.2             26.0  
3     71.4   196.6        3.850           18.0             22.0  
4     68.2   178.0        2.998           16.4             27.0  
..     ...     ...          ...            ...              ...  
152   67.6   176.6        3.042           15.8             25.0  
153   69.3   185.9        3.208           17.9             25.0  
154   69.3   186.2        3.259           17.9             25.0  
155   71.5   185.7        3.601           18.5             23.0  
156   72.1   189.8        3.600           21.1             24.0  

[157 rows x 14 columns]

In [22]:
pla.drop(['sl_no','hsc_b'], inplace=True, axis=1)

In [23]:
pla

gender  ssc_p    ssc_b  hsc_p     hsc_s  degree_p   degree_t workex  \
0        M  67.00   Others  91.00  Commerce     58.00   Sci&Tech     No   
1        M  79.33  Central  78.33   Science     77.48   Sci&Tech    Yes   
2        M  65.00  Central  68.00      Arts     64.00  Comm&Mgmt     No   
3        M  56.00  Central  52.00   Science     52.00   Sci&Tech     No   
4        M  85.80  Central  73.60  Commerce     73.30  Comm&Mgmt     No   
..     ...    ...      ...    ...       ...       ...        ...    ...   
210      M  80.60   Others  82.00  Commerce     77.60  Comm&Mgmt     No   
211      M  58.00   Others  60.00   Science     72.00   Sci&Tech     No   
212      M  67.00   Others  67.00  Commerce     73.00  Comm&Mgmt    Yes   
213      F  74.00   Others  66.00  Commerce     58.00  Comm&Mgmt     No   
214      M  62.00  Central  58.00   Science     53.00  Comm&Mgmt     No   

     etest_p specialisation  mba_p      status    salary  
0       55.0         Mkt&HR  58.80      Placed  270000.0  
1       86.5        Mkt&Fin  66.28      Placed  200000.0  
2       75.0        Mkt&Fin  57.80      Placed  250000.0  
3       66.0         Mkt&HR  59.43  Not Placed       NaN  
4       96.8        Mkt&Fin  55.50      Placed  425000.0  
..       ...            ...    ...         ...       ...  
210     91.0        Mkt&Fin  74.49      Placed  400000.0  
211     74.0        Mkt&Fin  53.62      Placed  275000.0  
212     59.0        Mkt&Fin  69.72      Placed  295000.0  
213     70.0         Mkt&HR  60.23      Placed  204000.0  
214     89.0         Mkt&HR  60.22  Not Placed       NaN  

[215 rows x 13 columns]

In [24]:
# Fetch the name of the model and the company name which have the lowest sales.

In [25]:
car

Manufacturer              Model  Sales in thousands   x_4_year  \
0    Acura          Integra                        16.919  16.360000   
1    Acura          TL                             39.384  19.875000   
2    Acura          CL                             14.114  18.225000   
3    Acura          RL                              8.588  29.725000   
4    Audi           A4                             20.397  22.255000   
..             ...                ...                 ...        ...   
152  Volvo          V40                             3.545  18.072975   
153  Volvo          S70                            15.245  18.072975   
154  Volvo          V70                            17.531  18.072975   
155  Volvo          C70                             3.493  18.072975   
156  Volvo          S80                            18.969  18.072975   

    Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  \
0      Passenger           21.500000          1.8       140.0      101.2   
1      Passenger           28.400000          3.2       225.0      108.1   
2      Passenger           27.390755          3.2       225.0      106.9   
3      Passenger           42.000000          3.5       210.0      114.6   
4      Passenger           23.990000          1.8       150.0      102.6   
..           ...                 ...          ...         ...        ...   
152    Passenger           24.400000          1.9       160.0      100.5   
153    Passenger           27.500000          2.4       168.0      104.9   
154    Passenger           28.800000          2.4       168.0      104.9   
155    Passenger           45.500000          2.3       236.0      104.9   
156    Passenger           36.000000          2.9       201.0      109.9   

     Width  Length  Curb weight  Fuel capacity  Fuel efficiency  
0     67.3   172.4        2.639           13.2             28.0  
1     70.3   192.9        3.517           17.2             25.0  
2     70.6   192.0        3.470           17.2             26.0  
3     71.4   196.6        3.850           18.0             22.0  
4     68.2   178.0        2.998           16.4             27.0  
..     ...     ...          ...            ...              ...  
152   67.6   176.6        3.042           15.8             25.0  
153   69.3   185.9        3.208           17.9             25.0  
154   69.3   186.2        3.259           17.9             25.0  
155   71.5   185.7        3.601           18.5             23.0  
156   72.1   189.8        3.600           21.1             24.0  

[157 rows x 14 columns]

In [26]:
car[['Manufacturer', 'Model','Sales in thousands']][car['Sales in thousands']==car['Sales in thousands'].min()]

Manufacturer              Model  Sales in thousands
83  Mitsubishi     3000GT                           0.11

In [27]:
# Fetch the name of the model and the company name which have the highest sales.

In [28]:
car[['Manufacturer', 'Model','Sales in thousands']][car['Sales in thousands']==car['Sales in thousands'].max()]

Manufacturer              Model  Sales in thousands
56  Ford           F-Series                      540.561

In [29]:
# Fetch the name of the model and company's name which have lowest sales with respect to Vehicle Type Passenger.

In [30]:
car1=car[['Manufacturer','Model','Sales in thousands',"Vehicle type"]][car["Vehicle type"]=="Passenger"]
car1[car['Sales in thousands']==car['Sales in thousands'].min()]

<ipython-input-30-e443fb9c49bb>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  car1[car['Sales in thousands']==car['Sales in thousands'].min()]


Manufacturer              Model  Sales in thousands Vehicle type
83  Mitsubishi     3000GT                           0.11    Passenger

In [31]:
# Fetch the name of the model and company's name which have Highest sales with respect to Engine Size > 6

In [32]:
car2=car[['Manufacturer','Model','Sales in thousands',"Engine size"]][car["Engine size"]>6]
car2=car2[car2['Sales in thousands']==car2['Sales in thousands'].max()]
car2

Manufacturer              Model  Sales in thousands  Engine size
39  Dodge          Viper                           0.916          8.0

In [34]:
# Fetch the company name who have got highest mileage with respect to Vehicle Type as Car

In [35]:
# Fuel efficiency=mileage*3.7854
car["Mileage"]=car["Fuel efficiency"]/3.7854
car.drop("Fuel efficiency",axis=1)

Manufacturer              Model  Sales in thousands   x_4_year  \
0    Acura          Integra                        16.919  16.360000   
1    Acura          TL                             39.384  19.875000   
2    Acura          CL                             14.114  18.225000   
3    Acura          RL                              8.588  29.725000   
4    Audi           A4                             20.397  22.255000   
..             ...                ...                 ...        ...   
152  Volvo          V40                             3.545  18.072975   
153  Volvo          S70                            15.245  18.072975   
154  Volvo          V70                            17.531  18.072975   
155  Volvo          C70                             3.493  18.072975   
156  Volvo          S80                            18.969  18.072975   

    Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  \
0      Passenger           21.500000          1.8       140.0      101.2   
1      Passenger           28.400000          3.2       225.0      108.1   
2      Passenger           27.390755          3.2       225.0      106.9   
3      Passenger           42.000000          3.5       210.0      114.6   
4      Passenger           23.990000          1.8       150.0      102.6   
..           ...                 ...          ...         ...        ...   
152    Passenger           24.400000          1.9       160.0      100.5   
153    Passenger           27.500000          2.4       168.0      104.9   
154    Passenger           28.800000          2.4       168.0      104.9   
155    Passenger           45.500000          2.3       236.0      104.9   
156    Passenger           36.000000          2.9       201.0      109.9   

     Width  Length  Curb weight  Fuel capacity   Mileage  
0     67.3   172.4        2.639           13.2  7.396840  
1     70.3   192.9        3.517           17.2  6.604322  
2     70.6   192.0        3.470           17.2  6.868495  
3     71.4   196.6        3.850           18.0  5.811803  
4     68.2   178.0        2.998           16.4  7.132668  
..     ...     ...          ...            ...       ...  
152   67.6   176.6        3.042           15.8  6.604322  
153   69.3   185.9        3.208           17.9  6.604322  
154   69.3   186.2        3.259           17.9  6.604322  
155   71.5   185.7        3.601           18.5  6.075976  
156   72.1   189.8        3.600           21.1  6.340149  

[157 rows x 14 columns]

In [36]:
car3=car[['Manufacturer',"Mileage"]][car["Vehicle type"]=="Car"]
car3[car3['Mileage']==car3['Mileage'].max()]

Manufacturer   Mileage
142  Toyota         7.132668

In [37]:
# Fetch the company name who has got lowest mileage with respect to Vehicle Type as Passengers.

In [38]:
car4=car[['Manufacturer',"Mileage"]][car["Vehicle type"]=="Passenger"]
car4[car4['Mileage']==car4['Mileage'].min()]

Manufacturer   Mileage
39  Dodge          4.226766

In [39]:
# Fetch the company name who has got least price and maximum number of sales figures.

In [40]:
car5=car[["Manufacturer","Price in thousands","Sales in thousands"]][car["Price in thousands"]==car["Price in thousands"].min()]
car5[["Manufacturer","Sales in thousands","Price in thousands"]][car5["Sales in thousands"]==car5["Sales in thousands"].max()]

Manufacturer  Sales in thousands  Price in thousands
26  Chevrolet                  21.855               9.235

In [41]:
# Fetch the company name who has got highest price with respect to minimum number of sales figures.

In [42]:
car6=car[["Manufacturer","Sales in thousands","Price in thousands"]][car["Sales in thousands"]==car["Sales in thousands"].min()]
car6[["Manufacturer","Price in thousands","Sales in thousands"]][car6["Price in thousands"]==car6["Price in thousands"].max()]

Manufacturer  Price in thousands  Sales in thousands
83  Mitsubishi                  25.45                0.11

In [ ]:
# Fetch the model who has got maximum number of Horsepower

In [43]:
car["Horsepower"].max()

450.0

In [ ]:
# Fetch the model and company name where the wheel base is maximum with Vehicle type as Car

In [44]:
car7=car[['Manufacturer',"Model","Vehicle type","Wheelbase"]][car["Vehicle type"]=="Car"]
car7[car7['Wheelbase']==car7['Wheelbase'].max()]

Manufacturer              Model Vehicle type  Wheelbase
40  Dodge          Ram Pickup                 Car      138.7

In [45]:
# Fetch the model and company name where the wheel base is minimum with Vehicle type as Passengers

In [46]:
car8=car[['Manufacturer',"Model","Vehicle type","Wheelbase"]][car["Vehicle type"]=="Passenger"]
car8[car8['Wheelbase']==car8['Wheelbase'].min()]

Manufacturer              Model Vehicle type  Wheelbase
125  Porsche        Carrera Coupe        Passenger       92.6
126  Porsche        Carrera Cabriolet    Passenger       92.6

In [47]:
# Fetch the model and company name where the curb weight is maximum with maximum mileage.

In [48]:
car9=car[['Manufacturer',"Model",'Mileage',"Curb weight"]][car["Curb weight"]==car["Curb weight"].max()]
car9[car9['Mileage']==car9['Mileage'].max()]

Manufacturer              Model   Mileage  Curb weight
18  Cadillac       Escalade           3.962593        5.572

In [ ]:
# Fetch the model and company name where the curb weight is minimum with minimum mileage

In [49]:
car11=car[['Manufacturer',"Model",'Mileage',"Curb weight"]][car["Curb weight"]==car["Curb weight"].min()]
car11[car11['Mileage']==car11['Mileage'].min()]

Manufacturer              Model    Mileage  Curb weight
26  Chevrolet      Metro              11.887779        1.895

In [50]:
 # Change the name of column x_4_year to 4_Year_Resale_Value

In [51]:
# car.replace(['x_4_year'], ['4_Year_Resale_Value'])
car.rename(columns={'x_4_year':'4_Year_Resale_Value'},inplace=True)
car

Manufacturer              Model  Sales in thousands  \
0    Acura          Integra                        16.919   
1    Acura          TL                             39.384   
2    Acura          CL                             14.114   
3    Acura          RL                              8.588   
4    Audi           A4                             20.397   
..             ...                ...                 ...   
152  Volvo          V40                             3.545   
153  Volvo          S70                            15.245   
154  Volvo          V70                            17.531   
155  Volvo          C70                             3.493   
156  Volvo          S80                            18.969   

     4_Year_Resale_Value Vehicle type  Price in thousands  Engine size  \
0              16.360000    Passenger           21.500000          1.8   
1              19.875000    Passenger           28.400000          3.2   
2              18.225000    Passenger           27.390755          3.2   
3              29.725000    Passenger           42.000000          3.5   
4              22.255000    Passenger           23.990000          1.8   
..                   ...          ...                 ...          ...   
152            18.072975    Passenger           24.400000          1.9   
153            18.072975    Passenger           27.500000          2.4   
154            18.072975    Passenger           28.800000          2.4   
155            18.072975    Passenger           45.500000          2.3   
156            18.072975    Passenger           36.000000          2.9   

     Horsepower  Wheelbase  Width  Length  Curb weight  Fuel capacity  \
0         140.0      101.2   67.3   172.4        2.639           13.2   
1         225.0      108.1   70.3   192.9        3.517           17.2   
2         225.0      106.9   70.6   192.0        3.470           17.2   
3         210.0      114.6   71.4   196.6        3.850           18.0   
4         150.0      102.6   68.2   178.0        2.998           16.4   
..          ...        ...    ...     ...          ...            ...   
152       160.0      100.5   67.6   176.6        3.042           15.8   
153       168.0      104.9   69.3   185.9        3.208           17.9   
154       168.0      104.9   69.3   186.2        3.259           17.9   
155       236.0      104.9   71.5   185.7        3.601           18.5   
156       201.0      109.9   72.1   189.8        3.600           21.1   

     Fuel efficiency   Mileage  
0               28.0  7.396840  
1               25.0  6.604322  
2               26.0  6.868495  
3               22.0  5.811803  
4               27.0  7.132668  
..               ...       ...  
152             25.0  6.604322  
153             25.0  6.604322  
154             25.0  6.604322  
155             23.0  6.075976  
156             24.0  6.340149  

[157 rows x 15 columns]

In [52]:
# Fetch the model and company name whose sales and Resale Value is Highest

In [57]:
car12=car[['Manufacturer',"Model",'Sales in thousands',"4_Year_Resale_Value"]][car["Sales in thousands"]==car["Sales in thousands"].max()]
car12[car12['4_Year_Resale_Value']==car12['4_Year_Resale_Value'].max()]

Manufacturer              Model  Sales in thousands  4_Year_Resale_Value
56  Ford           F-Series                      540.561               15.075

In [ ]:
# From Placement Data
# Fetch the data of the 5 highest salaries of Males.

In [58]:
pla

gender  ssc_p    ssc_b  hsc_p     hsc_s  degree_p   degree_t workex  \
0        M  67.00   Others  91.00  Commerce     58.00   Sci&Tech     No   
1        M  79.33  Central  78.33   Science     77.48   Sci&Tech    Yes   
2        M  65.00  Central  68.00      Arts     64.00  Comm&Mgmt     No   
3        M  56.00  Central  52.00   Science     52.00   Sci&Tech     No   
4        M  85.80  Central  73.60  Commerce     73.30  Comm&Mgmt     No   
..     ...    ...      ...    ...       ...       ...        ...    ...   
210      M  80.60   Others  82.00  Commerce     77.60  Comm&Mgmt     No   
211      M  58.00   Others  60.00   Science     72.00   Sci&Tech     No   
212      M  67.00   Others  67.00  Commerce     73.00  Comm&Mgmt    Yes   
213      F  74.00   Others  66.00  Commerce     58.00  Comm&Mgmt     No   
214      M  62.00  Central  58.00   Science     53.00  Comm&Mgmt     No   

     etest_p specialisation  mba_p      status    salary  
0       55.0         Mkt&HR  58.80      Placed  270000.0  
1       86.5        Mkt&Fin  66.28      Placed  200000.0  
2       75.0        Mkt&Fin  57.80      Placed  250000.0  
3       66.0         Mkt&HR  59.43  Not Placed       NaN  
4       96.8        Mkt&Fin  55.50      Placed  425000.0  
..       ...            ...    ...         ...       ...  
210     91.0        Mkt&Fin  74.49      Placed  400000.0  
211     74.0        Mkt&Fin  53.62      Placed  275000.0  
212     59.0        Mkt&Fin  69.72      Placed  295000.0  
213     70.0         Mkt&HR  60.23      Placed  204000.0  
214     89.0         Mkt&HR  60.22  Not Placed       NaN  

[215 rows x 13 columns]

In [60]:
pla1=pla[pla["gender"]=="M"]
pla1=pla1.sort_values(["salary"],ascending=False)
pla1["salary"].iloc[0:5]

119    940000.0
150    690000.0
77     500000.0
174    500000.0
163    500000.0
Name: salary, dtype: float64

In [ ]:
# Fetch the data of 5 lowest salaries of males.

In [61]:
pla2=pla[pla["gender"]=="M"]
pla2=pla2.sort_values(["salary"],ascending=True)
pla2["salary"].iloc[0:5]

1      200000.0
107    200000.0
47     204000.0
209    216000.0
73     218000.0
Name: salary, dtype: float64

In [ ]:
# Fetch the data of 15 lowest salaries of Female

In [62]:
pla3=pla[pla["gender"]=="F"]
pla3=pla3.sort_values(["salary"],ascending=False)
pla3["salary"].iloc[0:15]

177    650000.0
85     400000.0
21     393000.0
22     360000.0
131    360000.0
125    350000.0
37     320000.0
193    300000.0
23     300000.0
90     300000.0
102    300000.0
35     300000.0
96     300000.0
40     287000.0
113    280000.0
Name: salary, dtype: float64

In [64]:
# Fetch the data of 10 lowest salaries of  Females

In [65]:
pla4=pla[pla["gender"]=="F"]
pla4=pla4.sort_values(["salary"],ascending=True)
pla4["salary"].iloc[0:10]

15     200000.0
135    200000.0
50     200000.0
44     200000.0
213    204000.0
126    210000.0
204    210000.0
89     210000.0
88     210000.0
115    216000.0
Name: salary, dtype: float64

In [ ]:
# Fetch the data of  Highest salaries of commerce students who are Females

In [67]:
pla5=pla[(pla["hsc_s"]=="Commerce") & (pla["gender"]=="F")]
pla5[pla5["salary"]==pla5["salary"].max()]

gender  ssc_p    ssc_b  hsc_p     hsc_s  degree_p   degree_t workex  \
177      F   73.0  Central   97.0  Commerce      79.0  Comm&Mgmt    Yes   

     etest_p specialisation  mba_p  status    salary  
177     89.0        Mkt&Fin  70.81  Placed  650000.0

In [ ]:
# Fetch the data of  Highest salaries of arts students who are Females

In [68]:
pla6=pla[(pla["hsc_s"]=="Arts") & (pla["gender"]=="F")]
pla6[pla6["salary"]==pla6["salary"].max()]

gender  ssc_p    ssc_b  hsc_p hsc_s  degree_p degree_t workex  etest_p  \
193      F   60.0  Central   63.0  Arts      56.0   Others    Yes     80.0   

    specialisation  mba_p  status    salary  
193         Mkt&HR  56.63  Placed  300000.0

In [ ]:
# Fetch the data of lowest salaries of Commerce students who are Males

In [69]:
pla7=pla[(pla["hsc_s"]=="Commerce") & (pla["gender"]=="M")]
pla7[pla7["salary"]==pla7["salary"].min()]

gender  ssc_p   ssc_b  hsc_p     hsc_s  degree_p   degree_t workex  \
107      M   82.0  Others   90.0  Commerce      83.0  Comm&Mgmt     No   

     etest_p specialisation  mba_p  status    salary  
107     80.0         Mkt&HR  73.52  Placed  200000.0

In [ ]:
# Fetch the data of Lowest Salaries of Commerce students who have got Sci&Tec as their degree 

In [70]:
pla8=pla[(pla["hsc_s"]=="Commerce") & (pla["gender"]=="M") & (pla["degree_t"]=="Sci&Tech")]
pla8[pla8["salary"]==pla8["salary"].min()]

gender  ssc_p   ssc_b  hsc_p     hsc_s  degree_p  degree_t workex  etest_p  \
0      M   67.0  Others   91.0  Commerce      58.0  Sci&Tech     No     55.0   

  specialisation  mba_p  status    salary  
0         Mkt&HR   58.8  Placed  270000.0

In [ ]:
# Fetch the data of Highest Salaries of Commerce students who have got Sci&Tec as their degree and have no work experience

In [71]:
pla9=pla[(pla["hsc_s"]=="Commerce") & (pla["gender"]=="M") & (pla["degree_t"]=="Sci&Tech")&(pla["workex"]=="No")]
pla9[pla9["salary"]==pla9["salary"].max()]

gender  ssc_p   ssc_b  hsc_p     hsc_s  degree_p  degree_t workex  etest_p  \
0      M   67.0  Others   91.0  Commerce      58.0  Sci&Tech     No     55.0   

  specialisation  mba_p  status    salary  
0         Mkt&HR   58.8  Placed  270000.0

In [ ]:
# Fetch the data of Lowest Salaries of Science students who have got Commerce and Managemet as their degree and have work experience

In [72]:
pla11=pla[(pla["hsc_s"]=="Science") &(pla["gender"]=="F") & (pla["specialisation"]=="Mkt&HR")]
pla11[pla11["salary"]==pla11["salary"].min()]

gender  ssc_p    ssc_b  hsc_p    hsc_s  degree_p   degree_t workex  \
50       F   75.2  Central   73.2  Science      68.4  Comm&Mgmt     No   
135      F   72.0  Central   56.0  Science      69.0  Comm&Mgmt     No   

     etest_p specialisation  mba_p  status    salary  
50      65.0         Mkt&HR  62.98  Placed  200000.0  
135     55.6         Mkt&HR  65.63  Placed  200000.0

In [ ]:
# Fetch the data for Femals who have specialization in Marketing and HR and have got work Experience

In [73]:
pla11=pla[(pla["gender"]=="F") & (pla["specialisation"]=="Mkt&HR")& (pla["workex"]=="Yes")]
pla11

gender  ssc_p    ssc_b  hsc_p     hsc_s  degree_p   degree_t workex  \
41       F   74.0   Others  63.16  Commerce      65.0  Comm&Mgmt    Yes   
80       F   69.0   Others  62.00  Commerce      69.0  Comm&Mgmt    Yes   
89       F   84.0   Others  75.00   Science      69.0   Sci&Tech    Yes   
100      F   45.0   Others  57.00  Commerce      58.0  Comm&Mgmt    Yes   
121      F   64.0  Central  67.00   Science      69.6   Sci&Tech    Yes   
168      F   48.0  Central  51.00  Commerce      58.0  Comm&Mgmt    Yes   
193      F   60.0  Central  63.00      Arts      56.0     Others    Yes   

     etest_p specialisation  mba_p      status    salary  
41     65.00         Mkt&HR  69.76  Not Placed       NaN  
80     67.00         Mkt&HR  62.35      Placed  240000.0  
89     62.00         Mkt&HR  62.36      Placed  210000.0  
100    56.39         Mkt&HR  64.95  Not Placed       NaN  
121    55.67         Mkt&HR  71.49      Placed  250000.0  
168    60.00         Mkt&HR  58.79  Not Placed       NaN  
193    80.00         Mkt&HR  56.63      Placed  300000.0

In [ ]:
# Fetch the data who have got highest salary with no working experience

In [74]:
pla12=pla[(pla['workex']=="No")]
pla12[pla12["salary"]==pla12["salary"].max()]

gender  ssc_p   ssc_b  hsc_p    hsc_s  degree_p  degree_t workex  etest_p  \
163      M   63.0  Others   67.0  Science      64.0  Sci&Tech     No     75.0   

    specialisation  mba_p  status    salary  
163        Mkt&Fin  66.46  Placed  500000.0

In [ ]:
# Fetch the data who have got highest salary with working experience

In [75]:
pla13=pla[(pla['workex']=="Yes")]
pla13[pla13["salary"]==pla13["salary"].max()]

gender  ssc_p    ssc_b  hsc_p     hsc_s  degree_p   degree_t workex  \
119      M   60.8  Central   68.4  Commerce      64.6  Comm&Mgmt    Yes   

     etest_p specialisation  mba_p  status    salary  
119    82.66        Mkt&Fin  64.34  Placed  940000.0

In [ ]:
# Fetch the data who have got lowest salary with no working experience and has got degree in Science and Technology

In [77]:
pla14=pla[(pla['workex']=="No")& (pla["degree_t"]=="Sci&Tech")]
pla14[pla14["salary"]==pla14["salary"].min()]

gender  ssc_p    ssc_b  hsc_p    hsc_s  degree_p  degree_t workex  \
62       F   86.5   Others   64.2  Science      67.4  Sci&Tech     No   
117      M   77.0   Others   75.0  Science      73.0  Sci&Tech     No   
152      F   75.4   Others   60.5  Science      84.0  Sci&Tech     No   
202      M   70.0  Central   63.0  Science      66.0  Sci&Tech     No   

     etest_p specialisation  mba_p  status    salary  
62     59.00        Mkt&Fin  59.69  Placed  240000.0  
117    80.00        Mkt&Fin  67.05  Placed  240000.0  
152    98.00        Mkt&Fin  65.25  Placed  240000.0  
202    61.28         Mkt&HR  60.11  Placed  240000.0

In [ ]:
# Replace the observations in specialisation from Marketing & HR  to HR

In [78]:
pla.loc[pla['specialisation']=="Mkt&HR", 'specialisation'] = "HR"
pla

gender  ssc_p    ssc_b  hsc_p     hsc_s  degree_p   degree_t workex  \
0        M  67.00   Others  91.00  Commerce     58.00   Sci&Tech     No   
1        M  79.33  Central  78.33   Science     77.48   Sci&Tech    Yes   
2        M  65.00  Central  68.00      Arts     64.00  Comm&Mgmt     No   
3        M  56.00  Central  52.00   Science     52.00   Sci&Tech     No   
4        M  85.80  Central  73.60  Commerce     73.30  Comm&Mgmt     No   
..     ...    ...      ...    ...       ...       ...        ...    ...   
210      M  80.60   Others  82.00  Commerce     77.60  Comm&Mgmt     No   
211      M  58.00   Others  60.00   Science     72.00   Sci&Tech     No   
212      M  67.00   Others  67.00  Commerce     73.00  Comm&Mgmt    Yes   
213      F  74.00   Others  66.00  Commerce     58.00  Comm&Mgmt     No   
214      M  62.00  Central  58.00   Science     53.00  Comm&Mgmt     No   

     etest_p specialisation  mba_p      status    salary  
0       55.0             HR  58.80      Placed  270000.0  
1       86.5        Mkt&Fin  66.28      Placed  200000.0  
2       75.0        Mkt&Fin  57.80      Placed  250000.0  
3       66.0             HR  59.43  Not Placed       NaN  
4       96.8        Mkt&Fin  55.50      Placed  425000.0  
..       ...            ...    ...         ...       ...  
210     91.0        Mkt&Fin  74.49      Placed  400000.0  
211     74.0        Mkt&Fin  53.62      Placed  275000.0  
212     59.0        Mkt&Fin  69.72      Placed  295000.0  
213     70.0             HR  60.23      Placed  204000.0  
214     89.0             HR  60.22  Not Placed       NaN  

[215 rows x 13 columns]

In [ ]:
# Replace the observations in ssc_b from Others to PYTHON

In [81]:
pla.loc[pla['ssc_b']=="other", 'ssc_b'] = "Python"

In [ ]:
# Create an array range of 1 to 100.

In [83]:
arr=np.array(range(100))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#  Create a matrix of 10 rows and 10 columns


In [84]:
arr.shape

(100,)

In [85]:
arr=arr.reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# Print the following matrix from the colums

In [87]:
    [47, 48, 49],
a = [57, 58, 59],
    [67, 68, 69],

([67, 68, 69],)

In [88]:
a=np.array([47, 48, 49,57, 58, 59,67, 68, 69])
a

array([47, 48, 49, 57, 58, 59, 67, 68, 69])

In [89]:
a=a.reshape(3,3)
a

array([[47, 48, 49],
       [57, 58, 59],
       [67, 68, 69]])

In [90]:
c1=a[:,0]
print(c1)

[47 57 67]


In [91]:
c2=a[:,1]
print(c2)

[48 58 68]


In [92]:
c3=a[:,2]
print(c3)

[49 59 69]


In [94]:
    [40, 41, 42, 43,]
b = [50, 51, 52, 53,]
    [60, 61, 62, 63,]

[60, 61, 62, 63]

In [95]:
b = np.array([40, 41, 42, 43,50, 51, 52, 53,60, 61, 62, 63])
b

array([40, 41, 42, 43, 50, 51, 52, 53, 60, 61, 62, 63])

In [96]:
b=b.reshape(3,4)
b

array([[40, 41, 42, 43],
       [50, 51, 52, 53],
       [60, 61, 62, 63]])

In [97]:
c1=b[:,0]
print(c1)

[40 50 60]


In [98]:
c2=b[:,1]
print(c2)

[41 51 61]


In [99]:
c3=b[:,2]
print(c3)

[42 52 62]


In [100]:
c4=b[:,3]
print(c4)

[43 53 63]


In [103]:
    [32, 33, 34, 35, 36, 37, 38, 39],
    [42, 43, 44, 45, 46, 47, 48, 49],
c = [52, 53, 54, 55, 56, 57, 58, 59],
    [62, 63, 64, 65, 66, 67, 68, 69],
    [72, 73, 74, 75, 76, 77, 78, 79],

([72, 73, 74, 75, 76, 77, 78, 79],)

In [104]:
c= np.array([32, 33, 34, 35, 36, 37, 38, 39,42, 43, 44, 45, 46, 47, 48, 49,52, 53, 54, 55, 56, 57, 58, 59,62, 63, 64, 65, 66, 67, 68, 69,72, 73, 74, 75, 76, 77, 78, 79])
c

array([32, 33, 34, 35, 36, 37, 38, 39, 42, 43, 44, 45, 46, 47, 48, 49, 52,
       53, 54, 55, 56, 57, 58, 59, 62, 63, 64, 65, 66, 67, 68, 69, 72, 73,
       74, 75, 76, 77, 78, 79])

In [105]:
c= c.reshape(5,8)
c

array([[32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [52, 53, 54, 55, 56, 57, 58, 59],
       [62, 63, 64, 65, 66, 67, 68, 69],
       [72, 73, 74, 75, 76, 77, 78, 79]])

In [106]:
c1=c[:,0]
print(c1)

[32 42 52 62 72]


In [107]:
c2=c[:,1]
print(c2)

[33 43 53 63 73]


In [108]:
c3=c[:,2]
print(c3)

[34 44 54 64 74]


In [109]:
c4=c[:,3]
print(c4)

[35 45 55 65 75]


In [111]:
c5=c[:,4]
print(c5)

[36 46 56 66 76]


In [112]:
c6=c[:,5]
print(c6)

[37 47 57 67 77]


In [113]:
c7=c[:,6]
print(c7)

[38 48 58 68 78]


In [114]:
c8=c[:,7]
print(c8)

[39 49 59 69 79]


In [115]:

    [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
    [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
d = [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
    [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],

([50, 51, 52, 53, 54, 55, 56, 57, 58, 59],)

In [116]:
d=np.array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29,30, 31, 32, 33, 34, 35, 36, 37, 38, 39,40, 41, 42, 43, 44, 45, 46, 47, 48, 49,50, 51, 52, 53, 54, 55, 56, 57, 58, 59])
d

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

In [117]:
d=d.reshape(4,10)
d

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [118]:
d1=d[:,0]
print(d1)

[20 30 40 50]


In [119]:
d2=d[:,1]
print(d2)

[21 31 41 51]


In [120]:
d3=d[:,2]
print(d3)

[22 32 42 52]


In [121]:
d4=d[:,3]
print(d4)

[23 33 43 53]


In [122]:
d5=d[:,4]
print(d5)

[24 34 44 54]


In [123]:
d6=d[:,5]
print(d6)

[25 35 45 55]


In [124]:
d7=d[:,6]
print(d7)

[26 36 46 56]


In [125]:
d8=d[:,7]
print(d8)

[27 37 47 57]


In [126]:
d9=d[:,8]
print(d9)

[28 38 48 58]


In [127]:
d10=d[:,9]
print(d10)

[29 39 49 59]
